let
    // === FUENTE: BaseTicketsTI ===
    Source = BaseTicketsTI,

    // === SELECCIÓN DE COLUMNAS ===
    SelectedColumns =
    Table.SelectColumns(
        Source,
        {"Category"}
    ),

    // === ELIMINA VALORES NULOS O VACÍOS ===
    FilteredValidCategories =
    Table.SelectRows(
        SelectedColumns,
        each
            [Category] <> null and
            Text.Trim(Text.Clean([Category])) <> ""
    ),

    // === NORMALIZA LAS CATEGORIAS ===
    NormalizedCategories =
    Table.TransformColumns(
        FilteredValidCategories,
        {
            {
                "Category",
                each Text.Trim( Text.Clean( _ ) ),
                type text
            }
        }
    ),    

    // === ELIMINACIÓN DE DUPLICADOS ===
    DistinctCategories =
    Table.Distinct(
        NormalizedCategories
    ),
   
    // === ORDENA LAS CATEGORIAS (ESTABILIZA ID) ===
    SortedCategories =
    Table.Sort(
        DistinctCategories,
        {
            {"Category", Order.Ascending}
        }
    ),

    // === CREA IDENTIFICADOR ÚNICO ===
    AddedCategoryID =
    Table.AddIndexColumn(
        SortedCategories,
        "CategoryID",
        1,
        1,
        Int64.Type
    ),	

    // === REORDENACIÓN FINAL ===
    ReorderedColumns =
    Table.ReorderColumns(
        AddedCategoryID,
        {"CategoryID", "Category"}
    )

in
    ReorderedColumns